server:
  servlet:
    context-path: /community
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3376/community?serverTimezone=Asia/Shanghai
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  devtools:
    livereload:
      enabled: true
  mail:
    host: smtp.126.com
    port: 465
    username: your@email.com
    password: yourpassword
    protocol: smtps
    properties: {"mail.smtp.ssl.enable", true}
  redis:
    database: 11
    host: 192.168.3.19
    port: 6379
  kafka:
    bootstrap-servers: 192.168.3.19:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000

mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: me.echo.community.entity
  configuration:
    aggressive-lazy-loading: false
    use-generated-keys: true

logging:
  level:
    me.echo.community: debug

community:
  path:
    domain: http://localhost:8080
    upload: D:\\appLogs\\upload
